const taskList = [
  { name: "Task 1", completed: true },
  { name: "Task 2", completed: false },
  { name: "Task 3", completed: true },
  { name: "Task 4", completed: false },
  { name: "Task 5", completed: true },
  { name: "Task 6", completed: false },
  { name: "Task 7", completed: true },
  { name: "Task 8", completed: false },
  { name: "Task 9", completed: true },
  { name: "Task 10", completed: false },
  { name: "Task 11", completed: true },
  { name: "Task 12", completed: false },
  { name: "Task 13", completed: true },
  { name: "Task 14", completed: false },
  { name: "Task 15", completed: true },
  { name: "Task 16", completed: false },
  { name: "Task 17", completed: true },
  { name: "Task 18", completed: false },
  { name: "Task 19", completed: true },
  { name: "Task 20", completed: false },
  { name: "Task 21", completed: true },
  { name: "Task 22", completed: false },
  { name: "Task 23", completed: true },
  { name: "Task 24", completed: false },
  { name: "Task 25", completed: true },
  { name: "Task 26", completed: false },
  { name: "Task 27", completed: true },
  { name: "Task 28", completed: false },
  { name: "Task 29", completed: true },
  { name: "Task 30", completed: false },
];

module.exports = taskList;
